config/routes.rb
Antdesk::Application.routes.draw do
  get "administrator/index"

  devise_for :contributors, :controllers => { :sessions => "contributors/sessions" }
  namespace :contributors do
    resources :dashboard
    resources :applications do
      member do
        post :administrator
        get :new_administrator
      end
      resources :articles
      resources :videos
      resources :categories
    end
  end

  root :to => 'pages#index'
  resources :pages

   devise_for :admins, :controllers => { :sessions => "admins/sessions" }
   namespace :admins do
    resources :dashboard
    resources :applications
    resources :contributors do
      collection do
        get :auto
      end
    end
   end

  devise_for :users
  resources :articles
  resources :videos
  resources :categories

end

app/models/contributor.rb
class Contributor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_and_belongs_to_many :applications

  def self.search(search)
    where('contributor.email LIKE ?', "%#{search}%")
  end
end

app/controllers/admins/contributors_controller.rb
class Admins::ContributorsController < Admins::ApplicationController
  def auto
      contributors = Contributor.order(:name).where("name Like ?", "%#{params[:search]}%")
      render :json => contributors.map {|p| Hash[id: p.id, label: "#{p.name}", name: p.name]}
  end
  load_and_authorize_resource
  def show
    @contributors = Contributor.all
    respond_with(@contributors)
  end
end

app/controllers/contributors/application_controller.rb
# encoding: utf-8
require "application_responder"
class Contributors::ApplicationController < ActionController::Base
  helper :all
  self.responder = ApplicationResponder
  respond_to :html, :json, :xml
  WillPaginate.per_page = 10
  before_filter :authenticate_contributor!
  before_filter :find_application

  protect_from_forgery

  def current_ability
    @current_ability ||= ContributorAbility.new(current_contributor)
  end

  def find_application
    @application = current_contributor.applications.find(params[:application_id])
  end
end

app/controllers/contributors/applications_controller.rb
# encoding: utf-8
class Contributors::ApplicationsController < Contributors::ApplicationController
  load_and_authorize_resource
  skip_before_filter :find_application

  def show
    @application = @current_contributor.applications.find(params[:id])
    respond_with(@application)
  end


  #GET
  def new_administrator

  end

  #POST
  def administrator
    contributor = Contributor.find_by_email(params[:email])
    application = @current_contributor.applications.find(params[:id])
    if contributor.present?
      if application.contributors.include?(contributor)
        flash[:error] = "Bu kullanıcı daha önce eklenmiş bir daha ekleyemezsiniz."
      else
        if application.contributors << contributor
          flash[:success] = "#{contributor.name}, #{contributor.email} başarı ile eklendi."
        else
          flash[:error] = "Böyle bir kullanıcı yok."
        end
      end
    else
      flash[:error] = "Böyle bir kullanıcı yok."
    end
    respond_with(:contributors, application)
  end
end

app/controllers/contributors/articles_controller.rb
class Contributors::ArticlesController < Contributors::ApplicationController
  load_and_authorize_resource
  before_filter :find_application
  def index
    @articles = @application.articles.paginate(:page => params[:page])
    respond_with(:contributors, @application, @articles)
  end

  def show
    @article = @application.articles.find(params[:id])
    respond_with(:contributors, @application, @article)
  end

  def new
    @article = Article.new
    respond_with(:contributors, @application, @article)
  end

  def edit
    @article = @application.articles.find(params[:id])
  end

  def create
    @article = Article.new(params[:article])
    @article.save
    respond_with(:contributors, @application, @article)
  end

  def update
    @article = @application.articles.find(params[:id])
    @article.update_attributes(params[:article])
    respond_with(:contributors, @application, @article)
  end

  def destroy
    @article = @application.articles.find(params[:id])
    @article.destroy
    respond_with(:contributors, @application, @article)
  end

end

app/controllers/contributors/categories_controller.rb
class Contributors::CategoriesController < Contributors::ApplicationController

  load_and_authorize_resource
  def index
    @categories = @application.categories.paginate(:page => params[:page])
    respond_with(:contributors, @application, @categories)
  end

  def show
    @category = @application.categories.find(params[:id])
    respond_with(:contributors, @application, @category)
  end

  def new
    @category = Category.new
    respond_with(:contributors, @application, @category)
  end

  def edit
    @category = @application.categories.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])
    @category.application_id = @application.id
    @category.save
    respond_with(:contributors, @application, @category)
  end

  def update
    @category = @application.categories.find(params[:id])
    @category.update_attributes(params[:category])
    respond_with(:contributors, @application, @category)
  end

  def destroy
    @category = @application.categories.find(params[:id])
    @category.destroy
    respond_with(:contributors, @application, @category)
  end

end

app/controllers/contributors/dashboard_controller.rb
class Contributors::DashboardController < Contributors::ApplicationController
  skip_before_filter :find_application

  def index
    @applications = current_contributor.applications.paginate(:page => params[:page])
    respond_with(@applications)
  end
end

app/controllers/contributors/sessions_controller.rb
class Contributors::SessionsController < Devise::SessionsController

end

app/controllers/contributors/videos_controller.rb
class Contributors::VideosController < Contributors::ApplicationController
  load_and_authorize_resource
  before_filter :find_application
  def index
    @videos = @application.videos.paginate(:page => params[:page])
    respond_with(:contributors, @application, @videos)
  end

  def show
    @video = @application.videos.find(params[:id])
    respond_with(:contributors, @application, @video)
  end

  def new
    @video = Video.new
    respond_with(:contributors, @application, @video)
  end

  def edit
    @video = @application.videos.find(params[:id])
  end

  def create
    @video = Video.new(params[:video])
    @video.save
    respond_with(:contributors, @application, @video)
  end

  def update
    @video = @application.videos.find(params[:id])
    @video.update_attributes(params[:video])
    respond_with(:contributors, @application, @video)
  end

  def destroy
    @video = @application.videos.find(params[:id])
    @video.destroy
    respond_with(:contributors, @application, @video)
  end

end

app/helpers/contributors/articles_helper.rb
module Contributors::ArticlesHelper
end

app/helpers/contributors/categories_helper.rb
module Contributors::CategoriesHelper
end

app/helpers/contributors/dashboard_helper.rb
module Contributors::DashboardHelper
end

app/helpers/contributors/videos_helper.rb
module Contributors::VideosHelper
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/views/layouts/contributors/_nav.html.haml
%nav.navbar-inner
  .container
    %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.brand{:href => contributors_dashboard_index_path}
      = image_tag "logo.png"
      %span Antdesk
    .nav-collapse
      %ul.nav.pull-right
        -if @application.present?
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              %i.icon-plus.icon-white
              = t('tooltips.new')
              %b.caret
            %ul.dropdown-menu
              %li
                = link_to(new_contributors_application_category_path(@application), title: t('tooltips.new')) do
                  %i.icon-plus
                  =t('activerecord.models.category')
              %li
                = link_to(new_contributors_application_article_path(@application), title: t('tooltips.new')) do
                  %i.icon-plus
                  =t('activerecord.models.article')
              %li
                = link_to(new_contributors_application_video_path(@application), title: t('tooltips.new')) do
                  %i.icon-plus
                  =t('activerecord.models.video')
          %li.divider-vertical
          %li
            = link_to(contributors_application_categories_path(@application), title: t('categories')) do
              %i.icon-list.icon-white
              =t('categories')
          %li.divider-vertical
          %li
            = link_to(contributors_application_articles_path(@application), title: t('articles')) do
              %i.icon-book.icon-white
              =t('articles')
          %li.divider-vertical
          %li
            = link_to(contributors_application_videos_path(@application), title: t('videos')) do
              %i.icon-facetime-video.icon-white
              =t('videos')
          - if @application.owner_id == current_contributor.id
            %li.divider-vertical
            %li
              = link_to(new_administrator_contributors_application_path(@application), title: t('tooltips.add_to_administrator')) do
                %i.icon-user.icon-white
                = t('tooltips.add_to_administrator')
          %li.divider-vertical
        - if current_contributor
          %li.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
              %i.icon-user.icon-white
              = current_contributor.name
              %b.caret
            %ul.dropdown-menu
              %li= link_to t('nav.profile'), edit_contributor_registration_path
              %li= link_to t('nav.dashboard'), contributors_dashboard_index_path
              %li.divider
              %li= link_to t('nav.signout'), destroy_contributor_session_path, :method => :delete
        - else
          %li= link_to t('nav.signup'), new_contributor_registration_path
          %li= link_to t('nav.signin'), new_contributor_session_path

app/views/layouts/contributors/application.html.haml
!!!
%html{:lang => "en"}
  %head
    = render :partial => 'partials/head'
  %body
    / Header
    %header.navbar.navbar-fixed-top
      = render :partial => 'layouts/contributors/nav'
    / Messages
    = render :partial => 'partials/messages'
    / Contents
    .container
      .wrapper.row-fluid
        .span12.wrap
          .head
            .span2.pull-left
              = yield :toolbar_left
            .span8.title
              %h2= yield :title
            .span1.pull-right
              = yield :toolbar_right
            .clearfix
          = yield
    / Footer
    %footer
      = render :partial => 'partials/footer'