config/routes.rb
Antdesk::Application.routes.draw do
  get "administrator/index"

  devise_for :contributors, :controllers => { :sessions => "contributors/sessions" }
  namespace :contributors do
    resources :dashboard
    resources :applications do
      member do
        post :administrator
        get :new_administrator
      end
      resources :articles
      resources :videos
      resources :categories
    end
  end

  root :to => 'pages#index'
  resources :pages

   devise_for :admins, :controllers => { :sessions => "admins/sessions" }
   namespace :admins do
    resources :dashboard
    resources :applications
    resources :contributors do
      collection do
        get :auto
      end
    end
   end

  devise_for :users
  resources :articles
  resources :videos
  resources :categories

end

app/models/contributor.rb
class Contributor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_and_belongs_to_many :applications

  def self.search(search)
    where('contributor.email LIKE ?', "%#{search}%")
  end
end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :name, :youtube_id, :width, :height, :category_ids, :status

  has_and_belongs_to_many :categories

  validates_presence_of :name, :youtube_id, :width, :height, :categories

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  def self.search(search)
    where('videos.name LIKE ?', "%#{search}%")
  end

  scope :active, where(:status => true)
end

app/controllers/admins/contributors_controller.rb
class Admins::ContributorsController < Admins::ApplicationController
  def auto
      contributors = Contributor.order(:name).where("name Like ?", "%#{params[:search]}%")
      render :json => contributors.map {|p| Hash[id: p.id, label: "#{p.name}", name: p.name]}
  end
  load_and_authorize_resource
  def show
    @contributors = Contributor.all
    respond_with(@contributors)
  end
end

app/controllers/contributors/application_controller.rb
# encoding: utf-8
require "application_responder"
class Contributors::ApplicationController < ActionController::Base
  helper :all
  self.responder = ApplicationResponder
  respond_to :html, :json, :xml
  WillPaginate.per_page = 10
  before_filter :authenticate_contributor!
  before_filter :find_application

  protect_from_forgery

  def current_ability
    @current_ability ||= ContributorAbility.new(current_contributor)
  end

  def find_application
    @application = current_contributor.applications.find(params[:application_id])
  end
end

app/controllers/contributors/applications_controller.rb
# encoding: utf-8
class Contributors::ApplicationsController < Contributors::ApplicationController
  load_and_authorize_resource
  skip_before_filter :find_application

  def show
    @application = @current_contributor.applications.find(params[:id])
    respond_with(@application)
  end


  #GET
  def new_administrator

  end

  #POST
  def administrator
    contributor = Contributor.find_by_email(params[:email])
    application = @current_contributor.applications.find(params[:id])
    if contributor.present?
      if application.contributors.include?(contributor)
        flash[:error] = "Bu kullanıcı daha önce eklenmiş bir daha ekleyemezsiniz."
      else
        if application.contributors << contributor
          flash[:success] = "#{contributor.name}, #{contributor.email} başarı ile eklendi."
        else
          flash[:error] = "Böyle bir kullanıcı yok."
        end
      end
    else
      flash[:error] = "Böyle bir kullanıcı yok."
    end
    respond_with(:contributors, application)
  end
end

app/controllers/contributors/articles_controller.rb
class Contributors::ArticlesController < Contributors::ApplicationController
  load_and_authorize_resource
  before_filter :find_application
  def index
    @articles = @application.articles.paginate(:page => params[:page])
    respond_with(:contributors, @application, @articles)
  end

  def show
    @article = @application.articles.find(params[:id])
    respond_with(:contributors, @application, @article)
  end

  def new
    @article = Article.new
    respond_with(:contributors, @application, @article)
  end

  def edit
    @article = @application.articles.find(params[:id])
  end

  def create
    @article = Article.new(params[:article])
    @article.save
    respond_with(:contributors, @application, @article)
  end

  def update
    @article = @application.articles.find(params[:id])
    @article.update_attributes(params[:article])
    respond_with(:contributors, @application, @article)
  end

  def destroy
    @article = @application.articles.find(params[:id])
    @article.destroy
    respond_with(:contributors, @application, @article)
  end

end

app/controllers/contributors/categories_controller.rb
class Contributors::CategoriesController < Contributors::ApplicationController

  load_and_authorize_resource
  def index
    @categories = @application.categories.paginate(:page => params[:page])
    respond_with(:contributors, @application, @categories)
  end

  def show
    @category = @application.categories.find(params[:id])
    respond_with(:contributors, @application, @category)
  end

  def new
    @category = Category.new
    respond_with(:contributors, @application, @category)
  end

  def edit
    @category = @application.categories.find(params[:id])
  end

  def create
    @category = Category.new(params[:category])
    @category.application_id = @application.id
    @category.save
    respond_with(:contributors, @application, @category)
  end

  def update
    @category = @application.categories.find(params[:id])
    @category.update_attributes(params[:category])
    respond_with(:contributors, @application, @category)
  end

  def destroy
    @category = @application.categories.find(params[:id])
    @category.destroy
    respond_with(:contributors, @application, @category)
  end

end

app/controllers/contributors/dashboard_controller.rb
class Contributors::DashboardController < Contributors::ApplicationController
  skip_before_filter :find_application

  def index
    @applications = current_contributor.applications.paginate(:page => params[:page])
    respond_with(@applications)
  end
end

app/controllers/contributors/sessions_controller.rb
class Contributors::SessionsController < Devise::SessionsController

end

app/controllers/contributors/videos_controller.rb
class Contributors::VideosController < Contributors::ApplicationController
  load_and_authorize_resource
  before_filter :find_application
  def index
    @videos = @application.videos.paginate(:page => params[:page])
    respond_with(:contributors, @application, @videos)
  end

  def show
    @video = @application.videos.find(params[:id])
    respond_with(:contributors, @application, @video)
  end

  def new
    @video = Video.new
    respond_with(:contributors, @application, @video)
  end

  def edit
    @video = @application.videos.find(params[:id])
  end

  def create
    @video = Video.new(params[:video])
    @video.save
    respond_with(:contributors, @application, @video)
  end

  def update
    @video = @application.videos.find(params[:id])
    @video.update_attributes(params[:video])
    respond_with(:contributors, @application, @video)
  end

  def destroy
    @video = @application.videos.find(params[:id])
    @video.destroy
    respond_with(:contributors, @application, @video)
  end

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def show
    @video = @current_application.videos.active.find(params[:id])
    add_breadcrumb "Anasayfa", :root_path
    add_breadcrumb @video.categories.first.name, category_path(@video.categories.first)
    add_breadcrumb @video.name, :video_path
    respond_with(@video)
  end
end

app/helpers/contributors/articles_helper.rb
module Contributors::ArticlesHelper
end

app/helpers/contributors/categories_helper.rb
module Contributors::CategoriesHelper
end

app/helpers/contributors/dashboard_helper.rb
module Contributors::DashboardHelper
end

app/helpers/contributors/videos_helper.rb
module Contributors::VideosHelper
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/contributors/videos/_form.html.haml
= simple_form_for([:contributors, @application, @video], :defaults => {:input_html => {:class => 'span6', :rows => 3}}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :youtube_id
    = f.input :width, :input_html => { :value => 800 }
    = f.input :height, :input_html => { :value => 500 }
    = f.association :categories, :collection => @application.categories.all, :as => :check_boxes, :input_html => {:class => ''}
    = f.input :status, :inline_label => t('post'), :input_html => {:class => ''}


  .form-actions
    = f.button :submit

app/views/contributors/videos/edit.html.haml
= title t('tt.edit', resource_name: Video.model_name.human)
- content_for :toolbar_left do
  = link_to(contributors_application_videos_path(@application) , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
= render 'form'

app/views/contributors/videos/index.html.haml
= title t('tt.index', resource_name: Video.model_name.human)

- content_for :toolbar_left do
  = link_to(contributors_application_path(@application) , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left

%table.table.table-striped.table-bordered.table-condensed
  %tr
    %th
      = t('categories')
    %th
      = t('activerecord.attributes.video.name')
    %th
      = t('activerecord.attributes.video.status')
    %th{:width => "120px"}
  - @videos.each do |video|
    %tr
      %td
        - video.categories.each do |category|
          %span.label
            %i{:class => "#{category.icon_name}"}
            = "#{category.name}"
      %td= video.name
      %td= video.status ? t('published'):t('unpublished')
      %td
        = link_to(contributors_application_video_path(@application, video), class: 'btn', rel: 'tooltip', title: t('tooltips.show')) do
          %i.icon-eye-open
        = link_to(edit_contributors_application_video_path(@application, video) , class: 'btn', rel: 'tooltip', title: t('tooltips.edit')) do
          %i.icon-pencil
        = link_to(contributors_application_video_path(@application, video), class: 'btn', confirm: t('confirm'), method: :delete, rel: 'tooltip', title: t('tooltips.delete')) do
          %i.icon-trash
%hr/
= will_paginate @videos

app/views/contributors/videos/new.html.haml
= title t('tt.new', resource_name: Video.model_name.human)
- content_for :toolbar_left do
  = link_to(contributors_application_videos_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
= render 'form'

app/views/contributors/videos/show.html.haml
= title t('tt.show', resource_name: Video.model_name.human)

- content_for :toolbar_left do
  = link_to(contributors_application_videos_path , class: 'btn', rel: 'tooltip', title: t('tooltips.back')) do
    %i.icon-arrow-left
  = link_to(edit_contributors_application_video_path(@application, @video) , class: 'btn', rel: 'tooltip', title: t('tooltips.edit')) do
    %i.icon-pencil
  = link_to(contributors_application_video_path(@application, @video), class: 'btn', confirm: t('confirm'), method: :delete, rel: 'tooltip', title: t('tooltips.delete')) do
    %i.icon-trash

= show_for @video do |s|
  = s.attribute :name
  = s.association :categories
  = s.attribute :status do
    = @video.status ? t('published'):t('unpublished')
  = s.attribute :youtube_id
  = s.attribute :width
  = s.attribute :height