config/routes.rb
Antdesk::Application.routes.draw do
  get "administrator/index"

  devise_for :contributors, :controllers => { :sessions => "contributors/sessions" }
  namespace :contributors do
    resources :dashboard
    resources :applications do
      member do
        post :administrator
        get :new_administrator
      end
      resources :articles
      resources :videos
      resources :categories
    end
  end

  root :to => 'pages#index'
  resources :pages

   devise_for :admins, :controllers => { :sessions => "admins/sessions" }
   namespace :admins do
    resources :dashboard
    resources :applications
    resources :contributors do
      collection do
        get :auto
      end
    end
   end

  devise_for :users
  resources :articles
  resources :videos
  resources :categories

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :timeoutable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :remember_me, :name
  # attr_accessible :title, :body
end

app/models/admin_ability.rb
class AdminAbility

  include CanCan::Ability

  def initialize(user)
    can :manage, :all
  end
end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :cname_domain, :facebook_page, :name, :twitter_username, :logo, :owner_id, :owner_name, :subdomain
  has_and_belongs_to_many :contributors
  belongs_to :owner, :class_name => 'Contributor', :foreign_key => 'owner_id'
  has_many :categories, :dependent => :destroy

  has_many :videos, :through  => :categories, :uniq => true
  has_many :articles, :through => :categories, :uniq => true

  has_attached_file :logo, :default_url => "/assets/missing-image.jpg", :styles => {:small => "100x40#"}

  validates_attachment :logo, :presence => true
  validates :cname_domain, :uniqueness => true
  validates :subdomain, :uniqueness => true

  validates_presence_of :cname_domain, :facebook_page, :name, :twitter_username, :owner_name, :subdomain

  def owner_name
    owner.try(:name)
  end

  def owner_name=(name)
    self.owner = Contributor.find_by_name(name)
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :body, :name, :category_ids, :status

  has_and_belongs_to_many :categories

  validates_presence_of :name, :body, :categories

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  def self.search(search)
    where("articles.name LIKE ?", "%#{search}%")
  end

  scope :active, where(:status => true)
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :icon_name, :name,:application_id

  has_and_belongs_to_many :articles
  has_and_belongs_to_many :videos
  belongs_to :application

  validates_presence_of :name, :icon_name

  before_destroy {articles.clear}
  before_destroy {videos.clear}

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]
end

app/models/contributor.rb
class Contributor < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  # attr_accessible :title, :body

  has_and_belongs_to_many :applications

  def self.search(search)
    where('contributor.email LIKE ?', "%#{search}%")
  end
end

app/models/contributor_ability.rb
class ContributorAbility

  include CanCan::Ability

  def initialize(user)

    can :manage, Article #do |article|
      #article.application.contributors.include(user)
    #end
    can :manage, Category #do |category|
      #category.application.contributors.include(user)
    #end
    can :manage, Video #do |video|
      #video.application.contributors.include(user)
    #end
    can :manage, Application

  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  attr_accessible :email, :password, :password_confirmation, :remember_me, :name, :role_id

  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
  validates :email,
            :uniqueness => true,
            :format => {:with => EMAIL_REGEX}

  validates_presence_of :name

  belongs_to :role

  has_attached_file :avatar,
                    :default_url => "/assets/default-avatar.gif",
                    :styles => {
                        :small => "120x120#",
                    }

end

app/models/video.rb
class Video < ActiveRecord::Base
  attr_accessible :name, :youtube_id, :width, :height, :category_ids, :status

  has_and_belongs_to_many :categories

  validates_presence_of :name, :youtube_id, :width, :height, :categories

  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

  def self.search(search)
    where('videos.name LIKE ?', "%#{search}%")
  end

  scope :active, where(:status => true)
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def show
    @article = @current_application.articles.active.find(params[:id])
    add_breadcrumb "Anasayfa", :root_path
    add_breadcrumb @article.categories.first.name, category_path(@article.categories.first)
    add_breadcrumb @article.name, :article_path
    respond_with(@article)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_filter :authenticate_user!, :only => :index

  def index
    if params[:search]
      @search_articles = @current_application.articles.active.search(params[:search]).paginate(:page => params[:article_page])
      @search_videos = @current_application.videos.active.search(params[:search]).paginate(:page => params[:video_page])
      add_breadcrumb "Arama", :root_path
    elsif @current_application.present?
      @articles = @current_application.articles.active
      @videos = @current_application.videos.active
      add_breadcrumb "Anasayfa", :root_path
      respond_with(@current_application)
    end
  end
end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  def show
    @video = @current_application.videos.active.find(params[:id])
    add_breadcrumb "Anasayfa", :root_path
    add_breadcrumb @video.categories.first.name, category_path(@video.categories.first)
    add_breadcrumb @video.name, :video_path
    respond_with(@video)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for(:title) { page_title }
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  require 'redcarpet/compat'

  def markdown(text)
    options = [:hard_wrap, :filter_html, :autolink, :no_intraemphasis, :fenced_code, :gh_blockcode]
    Markdown.new(text, *options).to_html.html_safe
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contributors_helper.rb
module ContributorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/layouts/admins/_nav.html.haml
%nav.navbar-inner
  .container
    %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.brand{:href => admins_dashboard_index_path}
      = image_tag "logo.png"
      %span Antdesk
    .nav-collapse
      %ul.nav
        %li
          = link_to(new_admins_application_path, title: t('tooltips.new')) do
            %i.icon-plus.icon-white
            = t('tooltips.new')
            = t('activerecord.models.application')
        %li
          = link_to(admins_contributors_path, title: t('contributors')) do
            %i.icon-user.icon-white
            =t('contributors')
      %ul.nav.pull-right
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            %i.icon-user.icon-white
            = current_admin.name
            %b.caret
          %ul.dropdown-menu
            /%li= link_to t('nav.profile'), edit_admin_registration_path  TODO edit profile
            %li= link_to t('nav.dashboard'), admins_dashboard_index_path
            %li.divider
            %li= link_to t('nav.signout'),  destroy_admin_session_path, :method => :delete

app/views/layouts/admins/application.html.haml
!!!
%html{:lang => "en"}
  %head
    = render :partial => 'partials/head'
  %body
    / Header
    %header.navbar.navbar-fixed-top
      = render :partial => 'layouts/admins/nav'
    / Messages
    = render :partial => 'partials/messages'
    / Contents
    .container
      .wrapper.row-fluid
        .span12.wrap
          .head
            .span2.pull-left
              = yield :toolbar_left
            .span8.title
              %h2= yield :title
            .span1.pull-right
              = yield :toolbar_right
            .clearfix
            .clearfix
          = yield
    / Footer
    %footer
      = render :partial => 'partials/footer'

app/views/partials/_footer.html.haml
%p
#copyright.container.content
  .row-fluid
    .span8
      = t('all_rights_reserved')
      © 2012
      %strong
        - if @current_application
          = @current_application.name
    .span4
      .pull-right
        = t('prepare')
        %a{:href => "http://www.lab2023.com", :target => "blank"} lab2023 - internet teknolojileri

app/views/partials/_head.html.haml
%meta{:charset => "utf-8"}/
%meta{:content => "IE=edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
%meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
%title
  - if @current_application
    = @current_application.name
  - else
    AntDesk
%meta{:content => "", :name => "description"}/
%meta{:content => "", :name => "author"}/
= stylesheet_link_tag "application", :media => "all"
= javascript_include_tag "application"
= csrf_meta_tags
= yield :head

app/views/partials/_messages.html.haml
- if flash.count > 0
  .container
    .row-fluid
      - flash.each do |name, msg|
        %div{:class => "alert alert-#{name}"}
          %a.close{"data-dismiss" => "alert", :href => "#"} &times;
          = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/partials/_search.html.haml
%form.form-inline.row-fluid{:action => "#{pages_path}", :method => "get"}
  %input{:style => "width:80%;", :name => "search", :type => "text", :placeholder => t('placeholder')}
    %input.btn.btn-primary{:type => "submit", :value => "Ara"}

app/views/partials/_social.html.haml
%h2 Twitter
#tweets{:style =>"float:right"}
  #tweet
%script{:src => "http://twitterjs.googlecode.com/svn/trunk/src/twitter.min.js", :type => "text/javascript"}

:javascript
     getTwitters('tweet', {
       id: '#{@current_application.twitter_username}',
       count: 3,
       enableLinks: true,
       clearContents: true,
       template: '%text%'
     });


%h2 Facebook
.fb-like-box{"data-border-color" => "#ddd", "data-header" => "false", "data-href" => "#{@current_application.facebook_page}", "data-show-faces" => "true", "data-stream" => "false", "data-width" => "260"}